# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XOWEnhpBFu-nyrIYKWHFwSTMz9S_j2GX
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# Load the trained model
@st.cache_resource
def load_model():
    with open('model.pkl', 'rb') as file:
        return pickle.load(file)

model = load_model()

# App title
st.title("EEG Seizure Detection")

# File uploader
uploaded_file = st.file_uploader("Epileptic Seizure Recognition", type=["csv"])

if uploaded_file is not None:
    try:
        # Read data
        df = pd.read_csv(uploaded_file)

        # Drop non-numeric or ID columns
        if 'Unnamed' in df.columns:
            df = df.drop(columns=['Unnamed'])

        # Drop rows with missing values
        df.dropna(inplace=True)

        # Extract features
        X = df.drop(columns=['y'], errors='ignore')  # y might not be present in new data

        # Predict
        predictions = model.predict(X)

        # Display results
        st.success("Prediction Completed!")
        st.write("Predicted Seizure Classes:")
        st.write(predictions)

        # Optional: add histogram
        st.bar_chart(pd.Series(predictions).value_counts().sort_index())

    except Exception as e:
        st.error(f"An error occurred: {e}")