# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16oUiJOD3ZnP8TDI02x3QWWhc4CdwvPGL
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import os

# --- Title and Instructions ---
st.set_page_config(page_title="EEG Seizure Detection App", layout="centered")
st.title("🧠 EEG Seizure Detection")
st.markdown("""
Upload EEG data to predict seizure classes.

- ✅ CSV upload with error handling
- 📎 Sample dataset available for download
- 🧠 Choose a model (.pkl) or use the default one
- 🔮 Visualize predictions
""")

# --- Downloadable Sample Dataset ---
st.markdown("### 📎 [Download Sample EEG Dataset](https://github.com/Raghad2004Mohamed/ML_project?tab=readme-ov-file#csv-file)")

# --- Model Selection ---
st.sidebar.header("🔧 Model Options")
model_choice = st.sidebar.radio("Choose model option:", ["Use default model", "Upload your model (.pkl)"])

@st.cache_resource
def load_default_model():
    with open("model.pkl", "rb") as f:
        return pickle.load(f)

# Upload model if chosen
model = None
if model_choice == "Upload your model (.pkl)":
    uploaded_model = st.sidebar.file_uploader("Upload your model (.pkl)", type=["pkl"])
    if uploaded_model is not None:
        try:
            model = pickle.load(uploaded_model)
            st.sidebar.success("✅ Custom model loaded!")
        except Exception as e:
            st.sidebar.error(f"Error loading model: {e}")
else:
    model = load_default_model()

# --- Upload EEG Data File ---
st.markdown("### 📁 Upload EEG CSV File")
uploaded_file = st.file_uploader("Upload your EEG CSV file", type=["csv"])

if uploaded_file is not None and model is not None:
    try:
        df = pd.read_csv(uploaded_file)

        # Clean up columns
        df.columns = df.columns.str.strip()
        if 'Unnamed' in df.columns:
            df = df.drop(columns=[col for col in df.columns if 'Unnamed' in col])

        # Drop missing values
        df.dropna(inplace=True)

        # Handle label mapping (optional)
        label_map = {
            1: "Seizure",
            2: "No Seizure (EEG 1)",
            3: "No Seizure (EEG 2)",
            4: "No Seizure (EEG 3)",
            5: "No Seizure (Eyes Closed)"
        }

        X = df.drop(columns=['y'], errors='ignore')
        y_true = df['y'] if 'y' in df.columns else None

        # Predict
        predictions = model.predict(X)
        prediction_labels = [label_map.get(p, f"Class {p}") for p in predictions]

        # --- Display Results ---
        st.success("🔮 Predictions Complete")
        result_df = pd.DataFrame({"Prediction": predictions, "Label": prediction_labels})
        st.dataframe(result_df)

        # --- Pie Chart of Predictions ---
        st.markdown("### 📊 Prediction Summary")
        pie_data = result_df["Label"].value_counts()
        st.write(pie_data)
        st.plotly_chart(pie_data.plot.pie(autopct='%1.1f%%', figsize=(6, 6), ylabel='').figure)

    except Exception as e:
        st.error(f"❌ An error occurred while processing the file: {e}")

elif uploaded_file is not None and model is None:
    st.warning("⚠️ Please upload a valid model file.")